import React,{useState} from 'react';
import{ArrowUpRight,MessageCircle,Clock,ShieldCheck,History,CalendarDays,Wrench}from'lucide-react';
import{Brand,MONEY}from'./ui.jsx';
import{ICONS}from'./icons.mjs';
function Landing({config,services,reserve}){const[filter,setFilter]=useState('Todos');return <div className="landing">
 <header className="public-header"><a href="#"><Brand/></a><nav><a href="#servicios">Servicios</a><a href="#como">Cómo funciona</a><a href="#contacto">Contacto</a></nav><div className="header-actions"><a className="panel-link" href="#panel">Acceso al taller <ArrowUpRight size={15}/></a><button className="btn dark" onClick={()=>reserve()}>Reservar turno <ArrowUpRight size={16}/></button></div></header>
 <main><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="live-dot"/> TU AUTO EN BUENAS MANOS</div><h1>Menos vueltas.<br/>Más <span>kilómetros.</span></h1><p>Mantené tu auto al día, sin complicaciones.<br/>Elegí tu servicio, reservá un turno y nosotros<br className="desktop"/> nos ocupamos del resto.</p><div className="hero-buttons"><button className="btn dark large" onClick={()=>reserve()}>Reservar mi turno <ArrowUpRight size={20}/></button><a className="btn light large" href={`https://wa.me/${config.phone}`} target="_blank" rel="noreferrer"><MessageCircle size={19}/> Hablemos por WhatsApp</a></div><div className="hero-proof"><div className="avatar-stack"><span>MR</span><span>LF</span><span>DS</span></div><div><strong>Tu taller de confianza</strong><small>Atención cercana. Trabajo bien hecho.</small></div></div></div>
 <div className="hero-art"><div className="art-top"><span><span className="live-dot"/> LISTOS PARA EL PRÓXIMO VIAJE</span><span>01 / TF</span></div><div className="car-drawing"><svg viewBox="0 0 700 430" role="img" aria-label="Ilustración de un auto en el taller"><defs><linearGradient id="body" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#f8f9e9"/><stop offset="1" stopColor="#b9c7b9"/></linearGradient><linearGradient id="glass"><stop stopColor="#25473e"/><stop offset="1" stopColor="#5c7a66"/></linearGradient></defs><ellipse cx="350" cy="345" rx="263" ry="35" fill="#173e2c" opacity=".18"/><path d="M65 290L99 236L234 208L301 129Q318 117 368 117H460Q491 121 521 173L552 217L612 243Q631 254 632 283V315H66Z" fill="url(#body)" stroke="#263f35" strokeWidth="3"/><path d="M253 208L310 138H370V210Z M386 138H450Q475 141 501 188L514 210H386Z" fill="url(#glass)" stroke="#263f35" strokeWidth="3"/><path d="M239 216H545M378 216V300M520 220L544 295M125 249H213M71 286H160M219 306H472" fill="none" stroke="#7b9280" strokeWidth="3"/><path d="M594 247L615 256L621 269H584Z" fill="#d0eaa7"/><path d="M71 270L83 249H123L114 272Z" fill="#e6eece"/><rect x="403" y="231" width="28" height="6" rx="3" fill="#3c5648"/><rect x="95" y="300" width="512" height="15" rx="6" fill="#49614e"/><g fill="#22372d" stroke="#68816d" strokeWidth="4"><circle cx="193" cy="313" r="48"/><circle cx="522" cy="313" r="48"/></g><g fill="#b3c5b0" stroke="#647b67" strokeWidth="6"><circle cx="193" cy="313" r="27"/><circle cx="522" cy="313" r="27"/></g><g stroke="#587060" strokeWidth="5"><path d="M193 289V337M169 313H217M522 289V337M498 313H546"/></g><path d="M151 392H594M333 59V80M322 70H344M589 111V134M578 122H600" stroke="#b6cb78" strokeWidth="2" opacity=".7"/></svg></div><div className="art-service"><span className="mini-icon"><ShieldCheck size={22}/></span><div><strong>Todo bajo control</strong><small>Prevención hoy. Tranquilidad mañana.</small></div><span className="check-round"><Check size={16}/></span></div><div className="art-caption">MANTENIMIENTO INTELIGENTE <span>↗</span></div></div></section>
 <section className="trustbar"><span><ShieldCheck/>Profesionales de confianza</span><span><CalendarDays/>Turnos sin llamadas</span><span><History/>Historial de tu vehículo</span><span><MessageCircle/>Seguimiento por WhatsApp</span></section>
 <section id="servicios" className="services section"><div className="section-heading"><div><span className="eyebrow">UN TALLER, TODAS LAS SOLUCIONES</span><h2>¿Qué necesita tu auto?</h2></div><p>Desde el mantenimiento de siempre<br/>hasta ese ruido que no sabés de dónde viene.</p></div><div className="filters">{['Todos','Mantenimiento','Seguridad','Diagnóstico','Electricidad','Neumáticos','Confort'].map(f=><button key={f} onClick={()=>setFilter(f)} className={f===filter?'selected':''}>{f}</button>)}</div><div className="service-grid">{services.filter(s=>filter==='Todos'||s.category===filter).map((s,i)=>{const Icon=ICONS[s.icon]||Wrench;return <button className="service-card" key={s.id} onClick={()=>reserve(s)}><div className="service-top"><span className="service-icon"><Icon size={26}/></span><ArrowUpRight size={21}/></div><h3>{s.name}</h3><p>{s.description}</p><div className="service-bottom"><span><Clock size={13}/>{s.duration} min aprox.</span><strong>Desde {MONEY.format(s.price)}</strong></div></button>})}</div><p className="price-note">Precios ilustrativos de la demo. El presupuesto final depende del vehículo y se acuerda antes del trabajo.</p></section>
 <section id="como" className="how section"><div><span className="eyebrow">ASÍ DE SIMPLE</span><h2>Tu próximo servicio,<br/>en tres pasos.</h2><p>Sin esperas innecesarias.<br/>Sin sorpresas.</p></div><div className="steps">{[['01','Elegí lo que necesitás','Encontrá el servicio ideal para tu vehículo.'],['02','Pedí tu turno','Elegí día y horario. El taller lo confirma.'],['03','Dejá el resto en nuestras manos','Recibí novedades y recordatorios, si lo autorizás.']].map(x=><div className="step" key={x[0]}><span>{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div></div>)}</div></section>
 <section id="contacto" className="contact-banner"><div><span className="eyebrow">ESTAMOS PARA AYUDARTE</span><h2>¿No sabés por dónde empezar?</h2><p>Contanos qué le pasa a tu auto y lo vemos juntos.</p></div><a className="btn lime large" target="_blank" rel="noreferrer" href={`https://wa.me/${config.phone}`}><MessageCircle size={20}/> Consultar por WhatsApp <ArrowUpRight size={18}/></a></section></main>
 <footer><Brand/><p>{config.address}<br/>Lunes a viernes · {config.open}:00 a {config.close}:00</p><span>© {new Date().getFullYear()} TallerFlow · Hecho para seguir.</span></footer></div>}
export default Landing;
